# Generated by Django 5.2.7 on 2026-02-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_address_address_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': '收件地址', 'verbose_name_plural': '收件地址'},
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='鄉鎮市區'),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='郵遞區號'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='街道地址'),
        ),
        migrations.AddField(
            model_name='address',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
