# Generated by Django 5.2.7 on 2026-04-27 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_address_options_address_city_address_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=10, null=True, verbose_name='縣市')),
                ('district', models.CharField(blank=True, max_length=20, null=True, verbose_name='鄉鎮市區')),
                ('street_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='街道地址')),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='郵遞區號')),
                ('phone', models.CharField(max_length=20, verbose_name='手機號碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
        ),
    ]
