# Generated by Django 5.2.7 on 2025-11-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分類名稱')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='網址代稱')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.category', verbose_name='父分類')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '商品分類',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名稱')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='網址代稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='商品圖片')),
                ('stock', models.PositiveBigIntegerField(default=0, verbose_name='庫存數量')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_new', models.BooleanField(default=False, verbose_name='新品')),
                ('discount', models.IntegerField(blank=True, help_text='折扣百分比', null=True, verbose_name='折扣')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='分類')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='圖片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品圖片',
                'verbose_name_plural': '商品圖片',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_parent_name'),
        ),
    ]
