# Generated by Django 5.2.7 on 2025-11-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': '商品', 'verbose_name_plural': '商品管理'},
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='category_banner/', verbose_name='大圖橫幅'),
        ),
    ]
