# Generated by Django 5.2.7 on 2026-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_category_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_int',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='售價'),
        ),
    ]
