# Generated by Django 5.2.7 on 2026-01-08 09:01

from django.db import migrations
from decimal import Decimal, ROUND_DOWN


def covert_price_to_int(apps, schema_editor):
    Product = apps.get_model('product', 'Product')  # 他就像from product.model import Product
    
    for product in Product.objects.all():       # 把資料表每筆商品都拿出
        if product.price is not None:           # 如果product.price不是空的就做
            product.price_int = int(            # price_int
                Decimal(product.price).quantize(        # 使用Decimal可以精準的表示錢，float是「二進位」近似表示小數，而錢沒有近似
                    Decimal('1'),                       # quantize:我只要這個數字到某個精度
                    rounding = ROUND_DOWN       # ROUND_DOWN無條件捨去
                )
            )
            product.save(update_fields=['price_int'])




class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_price_int'),  # 一定要先執行0003才能跑，0003剛新增price_int欄位，如果沒增會壞掉!
    ]                                       # dependencies 保證「順序正確」

    operations = [
    ]



