# Generated by Django 5.2.7 on 2026-02-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20260108_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_int',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='售價'),
        ),
    ]
