# Generated by Django 5.2.7 on 2026-05-10 06:15

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'fixtures/initial_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_price_int_alter_product_price'),
    ]

    operations = [
        migrations.RunPython(load_fixture, migrations.RunPython.noop)
    ]
