# Generated by Django 5.2.7 on 2026-02-03 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_remove_product_price_int_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='訂單編號')),
                ('delivery_method', models.CharField(choices=[('711', '7-11 門市取貨'), ('home_delivery', '宅配')], max_length=20, verbose_name='配送方式')),
                ('payment_method', models.CharField(choices=[('cod', '貨到付款'), ('credit_card', '信用卡')], max_length=20, verbose_name='付款方式')),
                ('shipping_info', models.JSONField(default=dict, verbose_name='配送資訊')),
                ('payment_info', models.JSONField(default=dict, verbose_name='付款資訊')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品小計')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=60, max_digits=10, verbose_name='運費ˇ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總金額')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('shipped', '已出貨'), ('delivered', '已送達'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='訂單狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='單價')),
                ('subtotal', models.PositiveIntegerField(blank=True, verbose_name='小計')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='訂單')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
            },
        ),
    ]
