# Generated by Django 5.2.7 on 2026-02-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_address_options_address_city_address_district_and_more'),
        ('orders', '0002_alter_orderitem_price_alter_orderitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.address', verbose_name='配送地址'),
        ),
    ]
